name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      
      - name: Replace environment variables
        run: |
          # Replace the analytics variable in all files
          sed -i "s/ANALYTICS_TAG_PLACEHOLDER/${{ vars.ANALYTICS_TAG }}/g" index.markdown
          sed -i "s/ANALYTICS_TAG_PLACEHOLDER/${{ vars.ANALYTICS_TAG }}/g" _layouts/main.html
          sed -i "s/ANALYTICS_TAG_PLACEHOLDER/${{ vars.ANALYTICS_TAG }}/g" _layouts/project.html
          sed -i "s/ANALYTICS_TAG_PLACEHOLDER/${{ vars.ANALYTICS_TAG }}/g" projects/cad.md
          sed -i "s/ANALYTICS_TAG_PLACEHOLDER/${{ vars.ANALYTICS_TAG }}/g" projects/plonk.md
          sed -i "s/ANALYTICS_TAG_PLACEHOLDER/${{ vars.ANALYTICS_TAG }}/g" projects/scam.md
          
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 